name: Pytest Backend

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

env:
    AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
    MONGO_URI: "mongodb://localhost:27017"

jobs:
  pytest-backend:
    permissions:
        contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
          pip install coverage

      - name: Test with Pytest
        working-directory: ./backend
        run: coverage run -m pytest

      - name: Generate Coverage Report
        working-directory: ./backend
        run: coverage xml
  
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
            name: coverage
            path: ./backend/coverage.xml

      - name: Commit Coverage Report
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./backend/coverage.xml
          git commit -m "Auto update coverage report"
          git push